{
 "title": "Environment",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "AQI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "AQI" } },
   "targets": [
    {
     "expr": "avg_over_time(homeassistant_sensor_aqi_None{friendly_name!=\"AirNow AQI\"}[24h])",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "homeassistant_sensor_unit_aqi{friendly_name=\"AirNow AQI\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Particulates",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_u0xb5g_per_mu0xb3",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "homeassistant_sensor_pm25_u0xb5g_per_mu0xb3 - 1",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "homeassistant_sensor_pm1_u0xb5g_per_mu0xb3 - 1",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "homeassistant_sensor_pm10_u0xb5g_per_mu0xb3 - 1",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_carbon_dioxide_ppm > 0",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{friendly_name!~\"Bambu X1.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}