{
 "title": "Network",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Internet state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((mktxp_netwatch_status{routerboard_name=\"router\"} == bool 1) * 2) + on() ((mktxp_netwatch_status{routerboard_name=\"router-backup\"} == bool 1) * 1)"
    }
   ]
  },
  {
   "title": "Internet state",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "((mktxp_netwatch_status{routerboard_name=\"router\"} == bool 1) * 2) + on() ((mktxp_netwatch_status{routerboard_name=\"router-backup\"} == bool 1) * 1)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Green >= 99%\nYellow >= 97%\nRed >= 95%",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mktxp_netwatch_status{routerboard_name=\"router\"} == 1",
     "legendFormat": "Primary"
    },
    {
     "expr": "mktxp_netwatch_status{routerboard_name=\"router-backup\"} == 1",
     "legendFormat": "Backup"
    }
   ]
  },
  {
   "title": "WAN data usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ifTable_ifInOctets{agent_host=\"router.foxden.network\",ifName=\"wan\"}[30d])",
     "legendFormat": "RX"
    },
    {
     "expr": "increase(ifTable_ifOutOctets{agent_host=\"router.foxden.network\",ifName=\"wan\"}[30d])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "IPv6 data usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ifTable_ifInOctets{agent_host=\"router.foxden.network\",ifName=\"6to4-redfox\"}[30d]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(increase(ifTable_ifOutOctets{agent_host=\"router.foxden.network\",ifName=\"6to4-redfox\"}[30d]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ifTable_ifInErrors{agent_host=\"router.foxden.network\",ifName=\"wan\"}[$__rate_interval])",
     "legendFormat": "WAN RX Errors"
    },
    {
     "expr": "rate(ifTable_ifOutErrors{agent_host=\"router.foxden.network\",ifName=\"wan\"}[$__rate_interval])",
     "legendFormat": "WAN TX Errors"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (routerboard_name) (mktxp_netwatch_info > 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ifTable_ifInOctets{agent_host=\"router.foxden.network\",ifName=\"wan\"}[$__rate_interval])",
     "legendFormat": "WAN RX"
    },
    {
     "expr": "rate(ifTable_ifInOctets{agent_host=\"router.foxden.network\",ifName=\"6to4-redfox\"}[$__rate_interval])",
     "legendFormat": "IPv6 RX"
    },
    {
     "expr": "rate(ifTable_ifOutOctets{agent_host=\"router.foxden.network\",ifName=\"wan\"}[$__rate_interval])",
     "legendFormat": "WAN TX"
    },
    {
     "expr": "rate(ifTable_ifOutOctets{agent_host=\"router.foxden.network\",ifName=\"6to4-redfox\"}[$__rate_interval])",
     "legendFormat": "IPv6 TX"
    }
   ]
  }
 ]
}