{
 "title": "Timing status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UTC-TAI offset",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_timex_tai_offset_seconds{instance=\"ntpi.foxden.network:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NTP stratum",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_ntp_stratum", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "NTP sanity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_ntp_sanity", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PTP sync state",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "ptp4l_sync_state{instance=\"ntpi.foxden.network:9100\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Sync offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chrony_rms_offset{instance=\"ntpi.foxden.network:9100\"} * 1e9",
     "legendFormat": "CLOCK_REALTIME <- GPS"
    },
    {
     "expr": "ptp4l_sync_offset{instance=\"ntpi.foxden.network:9100\"}",
     "legendFormat": "eth0 <- GPS"
    }
   ]
  },
  {
   "title": "Sync frequency adjustment (absolute offset)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "expr": "(avg(node_timex_frequency_adjustment_ratio{instance=\"ntpi.foxden.network:9100\"}) - 1) * 1e9",
     "legendFormat": "CLOCK_REALTIME <- GPS"
    },
    {
     "expr": "avg(ptp4l_sync_frequency{instance=\"ntpi.foxden.network:9100\"})",
     "legendFormat": "eth0 <- GPS"
    },
    {
     "expr": "avg(node_thermal_zone_temp{instance=\"ntpi.foxden.network:9100\", zone=\"0\"})",
     "legendFormat": "CPU temperature"
    }
   ]
  }
 ]
}